<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f8d29f0b-d55e-4686-b0a7-05e73bcef6d4</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediLabo_Solutions.ExceptionHandler\MediLabo_Solutions.ExceptionHandler.csproj" />
  </ItemGroup>

  <Import Project="..\MediLabo_Solutions.Shared\MediLabo_Solutions.Shared.projitems" Label="Shared" />

</Project>
