# Consultez https://aka.ms/customizecontainer pour savoir comment personnaliser votre conteneur de débogage et comment Visual Studio utilise ce Dockerfile pour générer vos images afin d’accélérer le débogage.

# Cette phase est utilisée pour générer le projet de service
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

# Copier les fichiers de projets pour la restauration
COPY ["MediLabo_Solutions.Frontend/MediLabo_Solutions.Frontend.csproj", "MediLabo_Solutions.Frontend/"]
COPY ["MediLabo_Solutions.Shared/MediLabo_Solutions.Shared.shproj", "MediLabo_Solutions.Shared/"]
COPY ["MediLabo_Solutions.Shared/MediLabo_Solutions.Shared.projitems", "MediLabo_Solutions.Shared/"]

RUN dotnet restore "./MediLabo_Solutions.Frontend/MediLabo_Solutions.Frontend.csproj"

# Copier tout le code source
COPY . .
WORKDIR "/src/MediLabo_Solutions.Frontend"
RUN dotnet build "./MediLabo_Solutions.Frontend.csproj" -c $BUILD_CONFIGURATION -o /app/build

# Cette étape permet de publier le projet de service à copier dans la phase finale
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./MediLabo_Solutions.Frontend.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# Cette phase est utilisée en production ou lors de l’exécution à partir de VS en mode normal (par défaut quand la configuration de débogage n’est pas utilisée)
# Utiliser nginx pour servir les fichiers statiques
FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .

# Remplacer appsettings.json par la version Docker
RUN rm -f appsettings.json
COPY MediLabo_Solutions.Frontend/wwwroot/appsettings.Docker.json ./appsettings.json

COPY MediLabo_Solutions.Frontend/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80